name: prelura_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route:
  sizer: ^2.0.15
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.0
  visibility_detector: ^0.4.0+2
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.3
  intl: ^0.19.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  contentsize_tabbarview: ^0.0.2
  freezed_annotation:
  json_annotation:
  pull_to_refresh: ^2.0.0
  flutter_styled_toast: ^2.2.1
  shimmer: ^3.0.0
  geolocator: ^13.0.2
  flutter_portal: ^1.1.3
  logger:
  flutter_dotenv: ^5.0.2
  uuid:
  flutter_slidable: ^3.1.2
  flutter_stripe: ^11.0.0
  pinput: ^5.0.0
  lottie: 3.2.0
  skeletonizer: ^1.4.2

  graphql:
  gql_dio_link: ^1.0.1+1
  dio:
  rxdart:
  http:
  talker_dio_logger:
  cached_network_image: ^3.4.1
  share_plus: ^10.1.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications:
  shared_preferences: ^2.3.5
  hooks_riverpod: ^2.6.1
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  palette_generator: ^0.3.3+5
  camera: ^0.11.0+2
  video_player: ^2.9.2
  emoji_picker_flutter: ^4.2.0
  grouped_list: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator:
  build_runner: ^2.4.7
  freezed:
  json_serializable:
  graphql_codegen:
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.jpg"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#0C0F12"
  image: "assets/images/splash.png"
  image_dark: "assets/images/splash.png"
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    color_dark: "#0C0F12"
    color_dark_ios: "#0C0F12"
    image: "assets/images/splash.png"
    image_dark: "assets/images/splash.png"
    image_dark_ios: "assets/images/splash.png"
    # branding_mode: bottom
    branding_bottom_padding: 0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/animation/
    - assets/fonts/
    - assets/icons/
    - assets/icons/offer.svg
    - assets/images/
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/svgs/
    - assets/svgs/kids/
    - assets/svgs/men/
    - assets/svgs/women/

  fonts:
    - family: CourierPrime-Regular
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
    - family: Inter_18pt-Black
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
    - family: Inter_18pt-Bold
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
    - family: Inter_18pt-ExtraBold
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
    - family: Inter_18pt-Light
      fonts:
        - asset: assets/fonts/Inter_18pt-Light.ttf
    - family: Inter_18pt-Medium
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
    - family: Inter_18pt-Regular
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Inter_18pt-SemiBold
      fonts:
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
